BEGIN;

DROP TABLE IF EXISTS product_colors CASCADE;

DROP TABLE IF EXISTS colors CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS brands CASCADE;

DROP TYPE IF EXISTS product_status CASCADE;
DROP TYPE IF EXISTS color_status CASCADE;
DROP TYPE IF EXISTS brand_status CASCADE;

COMMIT;
